### ISSUE TITLE
wizard mechanic

### ISSUE THREAD

**Issue by smeerws** [therealunrealj/MyNumberWizard#2]
the restart button doesn't work, at the beginning, the first guess isn't shown

**Comment by therealunrealj** [comment]
Das Problem ist, ich versuchte bereits die Buttons zu vertauschen, jedoch bleiben die beiden immer noch vertauscht oder es erscheint irgendein neuer Fatal/Compiler Error.

Auch habe ich das Problem mit dem First Guess nicht lokalisieren und somit beheben können.

**Comment by smeerws** [comment]
hab die Fehler ausgebessert, bitte noch readme machen, siehe Kommentar pull request
